package com.github.cnrture.quickprojectwizard.gradle

sealed class Version(val name: String, val value: String) {
    data object Agp : Version("agp", "8.5.2")
    data object Kotlin : Version("kotlin", "2.0.20")
    data object CoreKtx : Version("core-ktx", "1.13.1")
    data object Junit : Version("junit", "4.13.2")
    data object JunitExt : Version("junit-ext", "1.2.1")
    data object EspressoCore : Version("espresso-core", "3.6.1")
    data object AppCompat : Version("appcompat", "1.7.0")
    data object Material : Version("material", "1.12.0")
    data object Ksp : Version("ksp", "2.0.20-1.0.24")
    data object LifecycleRuntimeKtx : Version("lifecycle-runtime-ktx", "2.8.4")
    data object ActivityCompose : Version("activity-compose", "1.9.1")
    data object ComposeBom : Version("compose-bom", "2024.08.00")
    data object Activity : Version("activity", "1.9.1")
    data object ConstraintLayout : Version("constraintlayout", "2.1.4")
    data object Coil : Version("coilVersion", "2.7.0")
    data object GlideXml : Version("glideVersion", "4.16.0")
    data object GlideCompose : Version("glideCompose", "1.0.0-beta01")
    data object Room : Version("room", "2.6.1")
    data object Retrofit : Version("retrofit", "2.11.0")
    data object Ktor : Version("ktor", "2.3.12")
    data object Hilt : Version("hilt", "2.52")
    data object HiltNavigationCompose : Version("hiltNavigationCompose", "1.2.0")
    data object Navigation : Version("navigation", "2.7.7")
    data object KtLint : Version("ktlint", "11.3.2")
    data object Detekt : Version("detekt", "1.23.5")
    data object GoogleServices : Version("googleServices", "4.4.2")
    data object Firebase : Version("firebase", "33.2.0")
    data object WorkManager : Version("workManagerVersion", "2.9.1")
}