package com.github.cnrture.quickprojectwizard.cmparch

object Template {
    const val ANDROID_MAIN_ACTIVITY = "android_main_activity.kt"
    const val ANDROID_MANIFEST = "android_manifest.xml"
    const val COMMON_APP = "common_app.kt"
    const val DESKTOP_MAIN = "desktop_main.kt"
    const val GRADLE_PROPERTIES = "gradle.properties"
    const val SETTINGS_GRADLE = "settings.gradle.kts"
    const val TOML = "libs.versions.toml"
    const val GRADLE_WRAPPER_PROPERTIES = "gradle_wrapper.properties"
    const val GRADLE_KTS = "project_build.gradle.kts"
    const val COMPOSE_GRADLE_KTS = "compose.gradle.kts"
    const val ANDROID_VALUES_XML = "values.xml"
    const val COMMON_COMPOSE_RESOURCES_MULTIPLATFORM_XML = "compose_multiplatform.xml"
    const val COMPOSE_IOS_MAIN = "compose_ios_main.kt"
    const val IOS_IOS_APP = "iosapp.swift"
    const val IOS_PROJECT = "project.pbxproj"
    const val IOS_APP_CONFIGURATION = "config.xcconfig"
    const val IOS_CONTENT_VIEW_SWIFT = "contentview.swift"
    const val IOS_ICONS_CONTENTS_JSON = "icons_contents.json"
    const val IOS_COLORS_CONTENTS_JSON = "colors_contents.json"
    const val IOS_ASSETS_CONTENTS_JSON = "assets_contents.json"
    const val IOS_PREVIEW_CONTENTS_JSON = "preview_contents.json"
    const val IOS_INFO_PLIST = "info.plist"
    const val REPOSITORY_IMPL = "repository_impl.kt"
    const val REPOSITORY = "repository.kt"
    const val CONSTANTS = "constants.kt"
    const val SERVICE = "service.kt"
    const val APP_MODULE = "app_module.kt"
    const val APPLICATION = "application.kt"
    const val NAVIGATION_GRAPH = "navigation_graph.kt"
    const val COMPOSE_SCREEN = "compose_screen.kt"
    const val COMPOSE_VIEW_MODEL = "compose_view_model.kt"
    const val CONTRACT = "contract.kt"
    const val MVI = "mvi.kt"
    const val MVI_DELEGATE = "mvi_delegate.kt"
    const val EMPTY_SCREEN = "empty_screen.kt"
    const val LOADING_BAR = "loading_bar.kt"
    const val IDEA_WORKSPACE = "idea_workspace.xml"
}