package com.github.cnrture.quickprojectwizard.toolwindow.manager.codesnippet.model

import androidx.compose.ui.graphics.Color

enum class CodeSnippetTheme(
    val displayName: String,
    val backgroundColor: Color,
    val windowBackgroundColor: Color,
    val textColor: Color,
    val keywordColor: Color,
    val stringColor: Color,
    val commentColor: Color,
    val numberColor: Color,
    val lineNumberColor: Color,
    val functionColor: Color,
    val classColor: Color,
    val variableColor: Color,
    val operatorColor: Color,
    val punctuationColor: Color,
) {
    MONOKAI(
        displayName = "Monokai",
        backgroundColor = Color(0xFF272822),
        windowBackgroundColor = Color(0xFF3E3D32),
        textColor = Color(0xFFF8F8F2),
        keywordColor = Color(0xFFFF6188),
        stringColor = Color(0xFFE6DB74),
        commentColor = Color(0xFF75715E),
        numberColor = Color(0xFFAE81FF),
        lineNumberColor = Color(0xFF75715E),
        functionColor = Color(0xFFA6E22E),
        classColor = Color(0xFF66D9EF),
        variableColor = Color(0xFFFD971F),
        operatorColor = Color(0xFFF92672),
        punctuationColor = Color(0xFFF8F8F2)
    ),

    DRACULA(
        displayName = "Dracula",
        backgroundColor = Color(0xFF282A36),
        windowBackgroundColor = Color(0xFF44475A),
        textColor = Color(0xFFF8F8F2),
        keywordColor = Color(0xFFFF79C6),
        stringColor = Color(0xFFF1FA8C),
        commentColor = Color(0xFF6272A4),
        numberColor = Color(0xFFBD93F9),
        lineNumberColor = Color(0xFF6272A4),
        functionColor = Color(0xFF50FA7B),
        classColor = Color(0xFF8BE9FD),
        variableColor = Color(0xFFFFB86C),
        operatorColor = Color(0xFFFF5555),
        punctuationColor = Color(0xFFF8F8F2)
    ),

    GITHUB_DARK(
        displayName = "GitHub Dark",
        backgroundColor = Color(0xFF0D1117),
        windowBackgroundColor = Color(0xFF21262D),
        textColor = Color(0xFFC9D1D9),
        keywordColor = Color(0xFFFF7B72),
        stringColor = Color(0xFFA5C25C),
        commentColor = Color(0xFF8B949E),
        numberColor = Color(0xFF79C0FF),
        lineNumberColor = Color(0xFF8B949E),
        functionColor = Color(0xFFD2A8FF),
        classColor = Color(0xFFFFA657),
        variableColor = Color(0xFF7EE787),
        operatorColor = Color(0xFF79C0FF),
        punctuationColor = Color(0xFFC9D1D9)
    ),

    SOLARIZED_DARK(
        displayName = "Solarized Dark",
        backgroundColor = Color(0xFF002B36),
        windowBackgroundColor = Color(0xFF073642),
        textColor = Color(0xFF839496),
        keywordColor = Color(0xFF268BD2),
        stringColor = Color(0xFF2AA198),
        commentColor = Color(0xFF586E75),
        numberColor = Color(0xFFD33682),
        lineNumberColor = Color(0xFF586E75),
        functionColor = Color(0xFF268BD2),
        classColor = Color(0xFF2AA198),
        variableColor = Color(0xFF839496),
        operatorColor = Color(0xFF268BD2),
        punctuationColor = Color(0xFF839496)
    ),

    NORD(
        displayName = "Nord",
        backgroundColor = Color(0xFF2E3440),
        windowBackgroundColor = Color(0xFF3B4252),
        textColor = Color(0xFFD8DEE9),
        keywordColor = Color(0xFF81A1C1),
        stringColor = Color(0xFFA3BE8C),
        commentColor = Color(0xFF616E88),
        numberColor = Color(0xFFB48EAD),
        lineNumberColor = Color(0xFF616E88),
        functionColor = Color(0xFF81A1C1),
        classColor = Color(0xFFEBCB8B),
        variableColor = Color(0xFFD8DEE9),
        operatorColor = Color(0xFF81A1C1),
        punctuationColor = Color(0xFFD8DEE9)
    ),

    MATERIAL_DARK(
        displayName = "Material Dark",
        backgroundColor = Color(0xFF212121),
        windowBackgroundColor = Color(0xFF424242),
        textColor = Color(0xFFEEFFFF),
        keywordColor = Color(0xFFC792EA),
        stringColor = Color(0xFFC3E88D),
        commentColor = Color(0xFF546E7A),
        numberColor = Color(0xFFF78C6C),
        lineNumberColor = Color(0xFF546E7A),
        functionColor = Color(0xFF82AAFF),
        classColor = Color(0xFFFFCB6B),
        variableColor = Color(0xFFECC48D),
        operatorColor = Color(0xFF89DDFF),
        punctuationColor = Color(0xFFEEFFFF)
    ),

    TOKYO_NIGHT_STORM(
        displayName = "Tokyo Storm",
        backgroundColor = Color(0xFF24283B),
        windowBackgroundColor = Color(0xFF1D202F),
        textColor = Color(0xFFA9B1D6),
        keywordColor = Color(0xFF7AA2F7),
        stringColor = Color(0xFF9ECE6A),
        commentColor = Color(0xFF565F89),
        numberColor = Color(0xFFFF9E64),
        lineNumberColor = Color(0xFF565F89),
        functionColor = Color(0xFF7DCFFF),
        classColor = Color(0xFFE0AF68),
        variableColor = Color(0xFFF7768E),
        operatorColor = Color(0xFFBB9AF7),
        punctuationColor = Color(0xFFA9B1D6)
    ),

    EVERFOREST_DARK(
        displayName = "Everforest",
        backgroundColor = Color(0xFF2D353B),
        windowBackgroundColor = Color(0xFF343F44),
        textColor = Color(0xFFD3C6AA),
        keywordColor = Color(0xFFE67E80),
        stringColor = Color(0xFFA7C080),
        commentColor = Color(0xFF859289),
        numberColor = Color(0xFFD699B6),
        lineNumberColor = Color(0xFF859289),
        functionColor = Color(0xFF7FBBB3),
        classColor = Color(0xFFDBBC7F),
        variableColor = Color(0xFFE69875),
        operatorColor = Color(0xFF83C092),
        punctuationColor = Color(0xFFD3C6AA)
    ),

    PALENIGHT(
        displayName = "Palenight",
        backgroundColor = Color(0xFF292D3E),
        windowBackgroundColor = Color(0xFF32364C),
        textColor = Color(0xFFBFC7D5),
        keywordColor = Color(0xFFC792EA),
        stringColor = Color(0xFFC3E88D),
        commentColor = Color(0xFF676E95),
        numberColor = Color(0xFFFFCB6B),
        lineNumberColor = Color(0xFF676E95),
        functionColor = Color(0xFF82B1FF),
        classColor = Color(0xFF005CC5),
        variableColor = Color(0xFFF78C6C),
        operatorColor = Color(0xFF89DDFF),
        punctuationColor = Color(0xFFBFC7D5)
    ),

    NIGHT_OWL(
        displayName = "Night Owl",
        backgroundColor = Color(0xFF011627),
        windowBackgroundColor = Color(0xFF001122),
        textColor = Color(0xFFD6DEEB),
        keywordColor = Color(0xFFC792EA),
        stringColor = Color(0xFFECC48D),
        commentColor = Color(0xFF637777),
        numberColor = Color(0xFFF78C6C),
        lineNumberColor = Color(0xFF637777),
        functionColor = Color(0xFFADDB67),
        classColor = Color(0xFFFFCB8B),
        variableColor = Color(0xFF7FDBCA),
        operatorColor = Color(0xFF7E57C2),
        punctuationColor = Color(0xFFD6DEEB)
    ),

    MOONLIGHT(
        displayName = "Moonlight",
        backgroundColor = Color(0xFF1E2030),
        windowBackgroundColor = Color(0xFF222436),
        textColor = Color(0xFFC8D3F5),
        keywordColor = Color(0xFFFCA7EA),
        stringColor = Color(0xFFC3E88D),
        commentColor = Color(0xFF7A88CF),
        numberColor = Color(0xFFFF966C),
        lineNumberColor = Color(0xFF7A88CF),
        functionColor = Color(0xFF65BCFF),
        classColor = Color(0xFFFFC777),
        variableColor = Color(0xFFF3E70F),
        operatorColor = Color(0xFF86E1FC),
        punctuationColor = Color(0xFFC8D3F5)
    ),

    HORIZON_DARK(
        displayName = "Horizon",
        backgroundColor = Color(0xFF1C1E26),
        windowBackgroundColor = Color(0xFF232530),
        textColor = Color(0xFFE95678),
        keywordColor = Color(0xFFB877DB),
        stringColor = Color(0xFF09F7A0),
        commentColor = Color(0xFF6C6F93),
        numberColor = Color(0xFFF09383),
        lineNumberColor = Color(0xFF6C6F93),
        functionColor = Color(0xFF25B2BC),
        classColor = Color(0xFFFAB795),
        variableColor = Color(0xFFE95678),
        operatorColor = Color(0xFF59E3E3),
        punctuationColor = Color(0xFFE95678)
    ),

    PANDA_SYNTAX(
        displayName = "Panda",
        backgroundColor = Color(0xFF292A2B),
        windowBackgroundColor = Color(0xFF31353A),
        textColor = Color(0xFFE6E6E6),
        keywordColor = Color(0xFFFF2C6D),
        stringColor = Color(0xFF19F9D8),
        commentColor = Color(0xFF676B79),
        numberColor = Color(0xFFFFB86C),
        lineNumberColor = Color(0xFF676B79),
        functionColor = Color(0xFF45A9F9),
        classColor = Color(0xFFB084EB),
        variableColor = Color(0xFFF1FA8C),
        operatorColor = Color(0xFFFF9AC1),
        punctuationColor = Color(0xFFE6E6E6)
    ),

    OUTRUN_ELECTRIC(
        displayName = "Outrun",
        backgroundColor = Color(0xFF0D0221),
        windowBackgroundColor = Color(0xFF1A0B3D),
        textColor = Color(0xFFB8B8B8),
        keywordColor = Color(0xFFFF0080),
        stringColor = Color(0xFF00FFFF),
        commentColor = Color(0xFF924C9D),
        numberColor = Color(0xFFFFD700),
        lineNumberColor = Color(0xFF924C9D),
        functionColor = Color(0xFF00BFFF),
        classColor = Color(0xFFFF6EC7),
        variableColor = Color(0xFF32CD32),
        operatorColor = Color(0xFFFF1493),
        punctuationColor = Color(0xFFB8B8B8)
    ),

    SHADES_OF_PURPLE(
        displayName = "Purple",
        backgroundColor = Color(0xFF2D2B55),
        windowBackgroundColor = Color(0xFF1E1E3F),
        textColor = Color(0xFFA599E9),
        keywordColor = Color(0xFFFF9D00),
        stringColor = Color(0xFF3AD900),
        commentColor = Color(0xFF6C7B95),
        numberColor = Color(0xFFFF6480),
        lineNumberColor = Color(0xFF6C7B95),
        functionColor = Color(0xFF17E5E6),
        classColor = Color(0xFFFAD000),
        variableColor = Color(0xFFFF628C),
        operatorColor = Color(0xFFB362FF),
        punctuationColor = Color(0xFFA599E9)
    ),

    NOCTIS_AZUREUS(
        displayName = "Noctis",
        backgroundColor = Color(0xFF0C111B),
        windowBackgroundColor = Color(0xFF16213E),
        textColor = Color(0xFF7ACAFF),
        keywordColor = Color(0xFF72F1B8),
        stringColor = Color(0xFFFFDA76),
        commentColor = Color(0xFF5C7E8C),
        numberColor = Color(0xFFFF75B5),
        lineNumberColor = Color(0xFF5C7E8C),
        functionColor = Color(0xFF36F9F6),
        classColor = Color(0xFF95E6CB),
        variableColor = Color(0xFFAAAAAA),
        operatorColor = Color(0xFFD5FF80),
        punctuationColor = Color(0xFF7ACAFF)
    ),

    GITHUB_LIGHT(
        displayName = "GitHub Light",
        backgroundColor = Color(0xFFFFFFFF),
        windowBackgroundColor = Color(0xFFF6F8FA),
        textColor = Color(0xFF24292F),
        keywordColor = Color(0xFFCF222E),
        stringColor = Color(0xFF0A3069),
        commentColor = Color(0xFF6E7781),
        numberColor = Color(0xFF0550AE),
        lineNumberColor = Color(0xFF6E7781),
        functionColor = Color(0xFF8250DF),
        classColor = Color(0xFF953800),
        variableColor = Color(0xFF116329),
        operatorColor = Color(0xFFCF222E),
        punctuationColor = Color(0xFF24292F)
    ),

    SOLARIZED_LIGHT(
        displayName = "Solarized Light",
        backgroundColor = Color(0xFFFDF6E3),
        windowBackgroundColor = Color(0xFFEEE8D5),
        textColor = Color(0xFF657B83),
        keywordColor = Color(0xFF268BD2),
        stringColor = Color(0xFF2AA198),
        commentColor = Color(0xFF93A1A1),
        numberColor = Color(0xFFD33682),
        lineNumberColor = Color(0xFF93A1A1),
        functionColor = Color(0xFF268BD2),
        classColor = Color(0xFF2AA198),
        variableColor = Color(0xFF657B83),
        operatorColor = Color(0xFF268BD2),
        punctuationColor = Color(0xFF657B83)
    ),

    TOKYO_NIGHT(
        displayName = "Tokyo Night",
        backgroundColor = Color(0xFF1A1B26),
        windowBackgroundColor = Color(0xFF24283B),
        textColor = Color(0xFFA9B1D6),
        keywordColor = Color(0xFF9D7CD8),
        stringColor = Color(0xFF9ECE6A),
        commentColor = Color(0xFF565F89),
        numberColor = Color(0xFFFF9E64),
        lineNumberColor = Color(0xFF565F89),
        functionColor = Color(0xFF7AA2F7),
        classColor = Color(0xFFE0AF68),
        variableColor = Color(0xFFF7768E),
        operatorColor = Color(0xFF89DDFF),
        punctuationColor = Color(0xFFA9B1D6)
    ),

    CATPPUCCIN_MOCHA(
        displayName = "Catppuccin Mocha",
        backgroundColor = Color(0xFF1E1E2E),
        windowBackgroundColor = Color(0xFF313244),
        textColor = Color(0xFFCDD6F4),
        keywordColor = Color(0xFFCBA6F7),
        stringColor = Color(0xFFA6E3A1),
        commentColor = Color(0xFF6C7086),
        numberColor = Color(0xFFFAB387),
        lineNumberColor = Color(0xFF6C7086),
        functionColor = Color(0xFF89B4FA),
        classColor = Color(0xFFF9E2AF),
        variableColor = Color(0xFFF38BA8),
        operatorColor = Color(0xFF94E2D5),
        punctuationColor = Color(0xFFCDD6F4)
    ),

    CYBERPUNK(
        displayName = "Cyberpunk",
        backgroundColor = Color(0xFF0A0E27),
        windowBackgroundColor = Color(0xFF1B263B),
        textColor = Color(0xFF00F5FF),
        keywordColor = Color(0xFFFF00FF),
        stringColor = Color(0xFF00FF41),
        commentColor = Color(0xFF6A4C93),
        numberColor = Color(0xFFFFD700),
        lineNumberColor = Color(0xFF6A4C93),
        functionColor = Color(0xFF00BFFF),
        classColor = Color(0xFFFF6B35),
        variableColor = Color(0xFFFF1744),
        operatorColor = Color(0xFF00E676),
        punctuationColor = Color(0xFF00F5FF)
    ),

    SYNTHWAVE(
        displayName = "Synthwave",
        backgroundColor = Color(0xFF2B213A),
        windowBackgroundColor = Color(0xFF3E2C41),
        textColor = Color(0xFFFFFFFF),
        keywordColor = Color(0xFFFF6EC7),
        stringColor = Color(0xFF19F9D8),
        commentColor = Color(0xFF848BBD),
        numberColor = Color(0xFFF97E72),
        lineNumberColor = Color(0xFF848BBD),
        functionColor = Color(0xFF36F9F6),
        classColor = Color(0xFFFEF100),
        variableColor = Color(0xFFFF9800),
        operatorColor = Color(0xFF7DF9FF),
        punctuationColor = Color(0xFFFFFFFF)
    ),

    ROSE_PINE(
        displayName = "Rosé Pine",
        backgroundColor = Color(0xFF191724),
        windowBackgroundColor = Color(0xFF1F1D2E),
        textColor = Color(0xFFE0DEF4),
        keywordColor = Color(0xFF31748F),
        stringColor = Color(0xFFF6C177),
        commentColor = Color(0xFF6E6A86),
        numberColor = Color(0xFF9CCFD8),
        lineNumberColor = Color(0xFF6E6A86),
        functionColor = Color(0xFFEBBCBA),
        classColor = Color(0xFFC4A7E7),
        variableColor = Color(0xFFEA6962),
        operatorColor = Color(0xFF56949F),
        punctuationColor = Color(0xFFE0DEF4)
    ),

    GRUVBOX_DARK(
        displayName = "Gruvbox Dark",
        backgroundColor = Color(0xFF282828),
        windowBackgroundColor = Color(0xFF3C3836),
        textColor = Color(0xFFF2E5BC),
        keywordColor = Color(0xFFD3869B),
        stringColor = Color(0xFFB8BB26),
        commentColor = Color(0xFF928374),
        numberColor = Color(0xFFD3869B),
        lineNumberColor = Color(0xFF928374),
        functionColor = Color(0xFF83A598),
        classColor = Color(0xFFFABD2F),
        variableColor = Color(0xFF8EC07C),
        operatorColor = Color(0xFFFE8019),
        punctuationColor = Color(0xFFF2E5BC)
    ),

    AURA_DARK(
        displayName = "Aura Dark",
        backgroundColor = Color(0xFF15141B),
        windowBackgroundColor = Color(0xFF1D1C26),
        textColor = Color(0xFFEDECEE),
        keywordColor = Color(0xFFA277FF),
        stringColor = Color(0xFF61FFCA),
        commentColor = Color(0xFF6D6D6D),
        numberColor = Color(0xFFFFCA85),
        lineNumberColor = Color(0xFF6D6D6D),
        functionColor = Color(0xFF82E2FF),
        classColor = Color(0xFFFFCA85),
        variableColor = Color(0xFFFF6767),
        operatorColor = Color(0xFF82E2FF),
        punctuationColor = Color(0xFFEDECEE)
    ),

    MATERIAL_OCEAN(
        displayName = "Material Ocean",
        backgroundColor = Color(0xFF0F111A),
        windowBackgroundColor = Color(0xFF1E2030),
        textColor = Color(0xFF8F93A2),
        keywordColor = Color(0xFFC792EA),
        stringColor = Color(0xFFC3E88D),
        commentColor = Color(0xFF464B5D),
        numberColor = Color(0xFFF78C6C),
        lineNumberColor = Color(0xFF464B5D),
        functionColor = Color(0xFF82AAFF),
        classColor = Color(0xFFFFCB6B),
        variableColor = Color(0xFFECC48D),
        operatorColor = Color(0xFF89DDFF),
        punctuationColor = Color(0xFF8F93A2)
    ),

    ONE_DARK_PRO(
        displayName = "One Dark Pro",
        backgroundColor = Color(0xFF1E2227),
        windowBackgroundColor = Color(0xFF2C313A),
        textColor = Color(0xFFABB2BF),
        keywordColor = Color(0xFFC678DD),
        stringColor = Color(0xFF98C379),
        commentColor = Color(0xFF5C6370),
        numberColor = Color(0xFFD19A66),
        lineNumberColor = Color(0xFF5C6370),
        functionColor = Color(0xFF61AFEF),
        classColor = Color(0xFFE5C07B),
        variableColor = Color(0xFFE06C75),
        operatorColor = Color(0xFF56B6C2),
        punctuationColor = Color(0xFFABB2BF)
    )
}
